// Code generated by gluagen. DO NOT EDIT.
package osbind

import (
	"os"
	lua "github.com/akzj/go-lua/pkg/lua"
)

// LuaOpen_os registers the "os" module.
func LuaOpen_os(L *lua.State) {
	lua.RegisterModule(L, "os", map[string]lua.Function{
		"chdir": lua_os_Chdir,
		"chmod": lua_os_Chmod,
		"chown": lua_os_Chown,
		"clearenv": lua_os_Clearenv,
		"environ": lua_os_Environ,
		"executable": lua_os_Executable,
		"exit": lua_os_Exit,
		"expand_env": lua_os_ExpandEnv,
		"getegid": lua_os_Getegid,
		"getenv": lua_os_Getenv,
		"geteuid": lua_os_Geteuid,
		"getgid": lua_os_Getgid,
		"getpagesize": lua_os_Getpagesize,
		"getpid": lua_os_Getpid,
		"getppid": lua_os_Getppid,
		"getuid": lua_os_Getuid,
		"getwd": lua_os_Getwd,
		"hostname": lua_os_Hostname,
		"is_path_separator": lua_os_IsPathSeparator,
		"lchown": lua_os_Lchown,
		"link": lua_os_Link,
		"lookup_env": lua_os_LookupEnv,
		"mkdir": lua_os_Mkdir,
		"mkdir_all": lua_os_MkdirAll,
		"mkdir_temp": lua_os_MkdirTemp,
		"read_file": lua_os_ReadFile,
		"readlink": lua_os_Readlink,
		"remove": lua_os_Remove,
		"remove_all": lua_os_RemoveAll,
		"rename": lua_os_Rename,
		"setenv": lua_os_Setenv,
		"symlink": lua_os_Symlink,
		"temp_dir": lua_os_TempDir,
		"truncate": lua_os_Truncate,
		"unsetenv": lua_os_Unsetenv,
		"user_cache_dir": lua_os_UserCacheDir,
		"user_config_dir": lua_os_UserConfigDir,
		"user_home_dir": lua_os_UserHomeDir,
		"write_file": lua_os_WriteFile,
	})
}

func lua_os_Chdir(L *lua.State) int {
	dir := L.CheckString(1)
	err := os.Chdir(dir)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Chmod(L *lua.State) int {
	name := L.CheckString(1)
	mode := os.FileMode(L.CheckInteger(2))
	err := os.Chmod(name, mode)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Chown(L *lua.State) int {
	name := L.CheckString(1)
	uid := int(L.CheckInteger(2))
	gid := int(L.CheckInteger(3))
	err := os.Chown(name, uid, gid)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Clearenv(L *lua.State) int {
	os.Clearenv()
	return 0
}

func lua_os_Environ(L *lua.State) int {
	result := os.Environ()
	luaPushStringSlice_os(L, result)
	return 1
}

func lua_os_Executable(L *lua.State) int {
	r0, err := os.Executable()
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_Exit(L *lua.State) int {
	code := int(L.CheckInteger(1))
	os.Exit(code)
	return 0
}

func lua_os_ExpandEnv(L *lua.State) int {
	s := L.CheckString(1)
	result := os.ExpandEnv(s)
	L.PushString(string(result))
	return 1
}

func lua_os_Getegid(L *lua.State) int {
	result := os.Getegid()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getenv(L *lua.State) int {
	key := L.CheckString(1)
	result := os.Getenv(key)
	L.PushString(string(result))
	return 1
}

func lua_os_Geteuid(L *lua.State) int {
	result := os.Geteuid()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getgid(L *lua.State) int {
	result := os.Getgid()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getpagesize(L *lua.State) int {
	result := os.Getpagesize()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getpid(L *lua.State) int {
	result := os.Getpid()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getppid(L *lua.State) int {
	result := os.Getppid()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getuid(L *lua.State) int {
	result := os.Getuid()
	L.PushInteger(int64(result))
	return 1
}

func lua_os_Getwd(L *lua.State) int {
	r0, err := os.Getwd()
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_Hostname(L *lua.State) int {
	r0, err := os.Hostname()
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_IsPathSeparator(L *lua.State) int {
	c := uint8(L.CheckInteger(1))
	result := os.IsPathSeparator(c)
	L.PushBoolean(bool(result))
	return 1
}

func lua_os_Lchown(L *lua.State) int {
	name := L.CheckString(1)
	uid := int(L.CheckInteger(2))
	gid := int(L.CheckInteger(3))
	err := os.Lchown(name, uid, gid)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Link(L *lua.State) int {
	oldname := L.CheckString(1)
	newname := L.CheckString(2)
	err := os.Link(oldname, newname)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_LookupEnv(L *lua.State) int {
	key := L.CheckString(1)
	r0, r1 := os.LookupEnv(key)
	L.PushString(string(r0))
	L.PushBoolean(bool(r1))
	return 2
}

func lua_os_Mkdir(L *lua.State) int {
	name := L.CheckString(1)
	perm := os.FileMode(L.CheckInteger(2))
	err := os.Mkdir(name, perm)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_MkdirAll(L *lua.State) int {
	path := L.CheckString(1)
	perm := os.FileMode(L.CheckInteger(2))
	err := os.MkdirAll(path, perm)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_MkdirTemp(L *lua.State) int {
	dir := L.CheckString(1)
	pattern := L.CheckString(2)
	r0, err := os.MkdirTemp(dir, pattern)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_ReadFile(L *lua.State) int {
	name := L.CheckString(1)
	r0, err := os.ReadFile(name)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_Readlink(L *lua.State) int {
	name := L.CheckString(1)
	r0, err := os.Readlink(name)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_Remove(L *lua.State) int {
	name := L.CheckString(1)
	err := os.Remove(name)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_RemoveAll(L *lua.State) int {
	path := L.CheckString(1)
	err := os.RemoveAll(path)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Rename(L *lua.State) int {
	oldpath := L.CheckString(1)
	newpath := L.CheckString(2)
	err := os.Rename(oldpath, newpath)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Setenv(L *lua.State) int {
	key := L.CheckString(1)
	value := L.CheckString(2)
	err := os.Setenv(key, value)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Symlink(L *lua.State) int {
	oldname := L.CheckString(1)
	newname := L.CheckString(2)
	err := os.Symlink(oldname, newname)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_TempDir(L *lua.State) int {
	result := os.TempDir()
	L.PushString(string(result))
	return 1
}

func lua_os_Truncate(L *lua.State) int {
	name := L.CheckString(1)
	size := L.CheckInteger(2)
	err := os.Truncate(name, size)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_Unsetenv(L *lua.State) int {
	key := L.CheckString(1)
	err := os.Unsetenv(key)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func lua_os_UserCacheDir(L *lua.State) int {
	r0, err := os.UserCacheDir()
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_UserConfigDir(L *lua.State) int {
	r0, err := os.UserConfigDir()
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_UserHomeDir(L *lua.State) int {
	r0, err := os.UserHomeDir()
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	L.PushString(string(r0))
	return 1
}

func lua_os_WriteFile(L *lua.State) int {
	name := L.CheckString(1)
	data := []byte(L.CheckString(2))
	perm := os.FileMode(L.CheckInteger(3))
	err := os.WriteFile(name, data, perm)
	if err != nil {
		L.PushNil()
		L.PushString(err.Error())
		return 2
	}
	return 0
}

func luaCheckStringSlice_os(L *lua.State, idx int) []string {
	L.CheckType(idx, lua.TypeTable)
	n := int(L.RawLen(idx))
	result := make([]string, 0, n)
	for i := 1; i <= n; i++ {
		L.GetI(idx, int64(i))
		s, _ := L.ToString(-1)
		result = append(result, s)
		L.Pop(1)
	}
	return result
}

func luaPushStringSlice_os(L *lua.State, ss []string) {
	L.CreateTable(len(ss), 0)
	for i, s := range ss {
		L.PushString(s)
		L.SetI(-2, int64(i+1))
	}
}

